#PBS -N test
#PBS -l nodes=1:ppn=2
#PBS -l mem=2G
#PBS -l walltime=7200:00:00
#PBS -q batch 
#PBS -V  
#PBS -m a -M wnm1503303791@gmail.com
#PBS -o /home/tuzhuo/code/git/basenji/tutorials/r
#PBS -e /home/tuzhuo/code/git/basenji/tutorials/r

cd /home/tuzhuo/code/git/basenji/tutorials
source activate basenji_env1

#python ../bin/basenji_hdf5_genes.py -g data/human.hg19.genome -l 131072 -c 0.333 -p 3 -t data/heart_wigs.txt -w 128 data/hg19.ml.fa data/gencode_chr9.gtf data/gencode_chr9.h5

python ../bin/basenji_test_genes.py -o output/gencode_chr9_test --rc -s --table models/params_small.txt models/heart/model_best.tf data/gencode_chr9.h5

cat output/gencode_chr9_test/gene_cors.txt
gunzip -c output/gencode_chr9_test/gene_table.txt.gz | head
